/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javazoom.jl.player.*;
import java.sql.DriverManager;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JFileChooser;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javazoom.jl.decoder.JavaLayerException;
/**
 *
 * @author Sarthak Agrawal
 */
public class main_frame extends javax.swing.JFrame {
private DefaultListModel model;
private DefaultListModel model_address;
int song_number=-1;
String bip;
FileInputStream FIS;
BufferedInputStream BIS;
long songlength = 0;
String table_name;
    /**
     * Creates new form frame3
     */
    public main_frame(String data_table_name) {
        table_name = data_table_name;
       initComponents();
       jList1.setVisible(false);
        model = new DefaultListModel();
        model_address = new DefaultListModel();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player","root","sarthak");
            Statement stmt = (Statement) con.createStatement();
            String query = "SELECT * FROM "+table_name+";";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String name = rs.getString("song_name");
                String location = rs.getString("location");
                location = location.replace("@","\\");
                String author = rs.getString("author");
                model.addElement(name + " - " + author);
                model_address.addElement(location);
              //  System.out.println(location);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
      listsongs.setModel(model);
      jList1.setModel(model_address);
              // ABOVE THESE COMMENTS... WILL BE USED WHEN ADDING DATA TO LIST
              // FROM THE MYSQL DATABASE EVERY TIME THIS PROGRAM RUNS
              listsongs.requestFocus();
        seek.setValue(0);
        {seek.update(seek.getGraphics());} 
    }
    private Player player;
    private main_frame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private void Stop()
    {
        if(player!=null)
            player.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        playbtn = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        seek = new javax.swing.JProgressBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listsongs = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();

        jToggleButton2.setText("jToggleButton2");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 242));
        setMinimumSize(new java.awt.Dimension(500, 620));
        getContentPane().setLayout(null);

        playbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/play.png"))); // NOI18N
        playbtn.setAutoscrolls(true);
        playbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        playbtn.setDisabledIcon(null);
        playbtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pause.png"))); // NOI18N
        playbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbtnActionPerformed(evt);
            }
        });
        getContentPane().add(playbtn);
        playbtn.setBounds(220, 480, 50, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/previous.png"))); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(92, 79));
        jButton5.setMinimumSize(new java.awt.Dimension(92, 79));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(125, 475, 70, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/next.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 480, 70, 40);
        getContentPane().add(seek);
        seek.setBounds(130, 540, 240, 14);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/list.jpg"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(400, 470, 40, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 470, 50, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/delete.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 470, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Screen Shot 2018-01-23 at 10.14.51 PM.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-15, 466, 620, 140);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Screen Shot 2018-01-22 at 10.13.22 PM.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-160, 0, 770, 610);

        listsongs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listsongs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listsongsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listsongs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 550, 410);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 10, 30, 30);

        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("Search for any song or author...");
        txt1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt1CaretUpdate(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt1);
        txt1.setBounds(150, 10, 260, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbtnActionPerformed
        // TODO add your handling code here:
        String song_location=null;
        if(playbtn.isSelected() && player!=null)
            player.notify();
        else if(playbtn.isSelected())
        {
            song_number = listsongs.getSelectedIndex();
            System.out.println(song_number);
            song_number++;
            playbtn.setText("pause");
            try{
                 Class.forName("java.sql.DriverManager");
                 java.sql.Connection con3 =(java.sql.Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player", "root", "sarthak");
                 java.sql.Statement stmt3 = (java.sql.Statement) con3.createStatement();
                 String query="select location from "+table_name+" where s_no = "+song_number+";";
                 ResultSet rs = stmt3.executeQuery(query);
                 if(rs.next())
                 { 
                   song_location = rs.getString("location");
                   song_location = song_location.replace("@","\\");
                   //JOptionPane.showMessageDialog(null,song_location);
                 }
                 else{
                     JOptionPane.showMessageDialog(null,"Couldn't retrieve song location");
                     playbtn.setSelected(false);
                 }
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
          /*  bip = song_location;
            Media hit = new Media(new File(bip).toURI().toString());
            MediaPlayer mediaPlayer = new MediaPlayer(hit);
            mediaPlayer.play; */
          
           // above code did not play mp3 files or wav file, now adding jlayer jar ...
          String song_location1 = song_location;
        try{
           /* FIS = new FileInputStream(song_location);
            BIS = new BufferedInputStream(FIS);
            player = new Player(BIS);*/
            new Thread(){
                public void run(){
                    try {
                        FIS = new FileInputStream(song_location1);
                        BIS = new BufferedInputStream(FIS);
                        player = new Player(BIS);
                        player.play();
                        } catch (JavaLayerException ex) {
                        Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                    }.start();
            new Thread(){
                public void run(){
                        int seek_total = 0;
                    try {
                        seek_total = FIS.available();
                    } catch (IOException ex) {
                        Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
                    }   
                    //JOptionPane.showMessageDialog(null,seek_total);
                        seek.setMaximum(seek_total);
                        while(player!=null){
                            try {
				Thread.sleep(100);
				int currentSecond = (int) FIS.available(); 
				seek.setValue(seek_total-currentSecond);
                                {seek.update(seek.getGraphics());}
                                System.out.println(seek_total-currentSecond);
					
				 
                            }catch (InterruptedException ex) {
				ex.printStackTrace();
				seek.setValue(0);
                                {seek.update(seek.getGraphics());}
			}   catch (IOException ex) {
                                Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
                            }
          }
        {seek.update(seek.getGraphics());}
        }
                    }.start();           
        /* } catch (JavaLayerException ex) {
                        Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }.start();*/
          /*  
            while(player!= null)
                {
                    try {
                        songlength = FIS.available();
                    } catch (IOException ex) {            
                        Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
                      }
                    System.out.println(songlength);
                }
                songlength = FIS.available();
                System.out.println();  // this should see how much song is left to be played.
                        // not ready...
            */
          
          // trying to add a seek bar through a different way. 
          
        }catch(Exception e){
            seek.setValue(0);
            {seek.update(seek.getGraphics());}
            System.out.println(e);
           }
        }
        else
        {
            playbtn.setText("play");
            seek.setMaximum(100);
            seek.setValue(0);
            {seek.update(seek.getGraphics());}
                player.close();
        }
    }//GEN-LAST:event_playbtnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            jLabel1.setVisible(false);
            
        }
        else {
        jLabel1.setVisible(true);
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        // do nothing.
    }//GEN-LAST:event_txt1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(player!=null){
            int current = listsongs.getSelectedIndex();
            listsongs.setSelectedIndex(++current);
            listsongs.updateUI();
            playbtn.doClick();
        }
        else{
            listsongs.setSelectedIndex(0);
            listsongs.updateUI();
            playbtn.doClick();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);
        File selectedFile = fileChooser.getSelectedFile();
        String file_path  = selectedFile.getAbsolutePath();
        file_path = file_path.replace("\\","@");
        String song_name = selectedFile.getName();
        String author = JOptionPane.showInputDialog(null,"Input song's author");
        //.println(file_path +'\n' + song_name + '\n'+ author);
        int s_no1 = 0;
        try
        {
                 Class.forName("java.sql.DriverManager");
                 java.sql.Connection con0 =(java.sql.Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player", "root", "sarthak");
                 java.sql.Statement stmt0 = (java.sql.Statement) con0.createStatement();
                 String query="select max(s_no) from "+table_name+";";
                 ResultSet rs = stmt0.executeQuery(query);
                 if(rs.next())
                      s_no1 = Integer.parseInt(rs.getString("max(s_no)"));
                 else
                     JOptionPane.showMessageDialog(null,"couldn't retrieve previous max s.no");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        ++s_no1;
        // now adding the new song , previous coding is for retrieving max s.no in previous records.
        try
        {
                 Class.forName("java.sql.DriverManager");
                 java.sql.Connection con2 =(java.sql.Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player", "root", "sarthak");
                 java.sql.Statement stmt2 = (java.sql.Statement) con2.createStatement();
                 //first//String query="INSERT INTO DATA VALUES('"+song_name+"','"+selectedFile.getAbsolutePath()+"','"+author+"');";
                 String query="INSERT INTO "+table_name+" VALUES('"+song_name+"','"+file_path+"','"+author+"','"+s_no1+"');";
                 stmt2.executeUpdate(query);
                 JOptionPane.showMessageDialog(null,"Song has been added to your list!");
                 System.out.println(file_path);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        if(player!=null){
        player.close();
        player = null;
        playbtn.setSelected(false);
        playbtn.setText("play");}
        /* new main_frame().setVisible(true);           //this was used before the application was made to be used by different people.
        main_frame.this.dispose();*/                      
                                     
        //SwingUtilities.updateComponentTreeUI(this);              this did not work.
                                     
      // System.out.println("Selected file path:" + selectedFile.getAbsolutePath());
      //  System.out.println("Selected file name: " + selectedFile.getName());
        model = new DefaultListModel();
        model_address = new DefaultListModel();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player","root","sarthak");
            Statement stmt = (Statement) con.createStatement();
            String query = "SELECT * FROM "+table_name+";";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String name = rs.getString("song_name");
                String location = rs.getString("location");
                location = location.replace("@","\\");
                String author1 = rs.getString("author");
                model.addElement(name + " - " + author1);
                model_address.addElement(location);
              //  System.out.println(location);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
      listsongs.setModel(model);
      jList1.setModel(model_address);
      listsongs.requestFocus();
      seek.setValue(0);
      {seek.update(seek.getGraphics());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt1CaretUpdate
        // TODO add your handling code here:
        String s = txt1.getText();
        if(s.equals("Search for any song or author...")){
            txt1.setText("");
            txt1.setHorizontalAlignment(0); //check this 
        }
        String criteria = txt1.getText();
        System.out.println(criteria);
        if(criteria.isEmpty() || criteria.equals("") || criteria.equals(" ") || criteria.equals("\n") || criteria.equals("all")){
            try{
                Class.forName("java.sql.DriverManager");
                 java.sql.Connection con7 =(java.sql.Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player", "root", "sarthak");
                 java.sql.Statement stmt7 = (java.sql.Statement) con7.createStatement();
                 String query7="select * from "+table_name+";";
                 ResultSet rs7 = stmt7.executeQuery(query7);
                 while(rs7.next()){
                 String name = rs7.getString("song_name");
                 String location = rs7.getString("location");
                 location = location.replace("@","\\");
                 String author = rs7.getString("author");
                 //model.clear();
                 //model.addElement(name + " - " + author);
                 //model_address.addElement(location);
              //  System.out.println(location);
            }
            }catch(Exception e){
                System.out.println(e);
            }
        }
        else{    
            try{
                Class.forName("java.sql.DriverManager");
                 java.sql.Connection con7 =(java.sql.Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/sound_player", "root", "sarthak");
                 java.sql.Statement stmt7 = (java.sql.Statement) con7.createStatement();
                 String query7="select * from "+table_name+" where song_name like '%"+criteria+"%' OR author like '%"+criteria+"%';";
                 ResultSet rs7 = stmt7.executeQuery(query7);
                 model.clear();
                 while(rs7.next()){
                 String name = rs7.getString("song_name");
                 String location = rs7.getString("location");
                 location = location.replace("@","\\");
                 String author = rs7.getString("author");
                 model.addElement(name + " - " + author);
                 model_address.addElement(location);
              //  System.out.println(location);
            }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_txt1CaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(player!=null){
        player.close();
        player = null;
        playbtn.setSelected(false);
        playbtn.setText("play");}
        int i;
        i = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete the selected song?");
        if(i==0 && song_number>=0)
        {
            try {
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con =(java.sql.Connection)
                        DriverManager.getConnection
                            ("jdbc:mysql://localhost:3306/sound_player", "root", "sarthak");
                java.sql.Statement stmt = (java.sql.Statement) con.createStatement();
                String query="delete from "+table_name+" where s_no = '"+song_number+"';";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"selected song has been deleted!");
                String query2 = "Select s_no from "+table_name+";";
                ResultSet rs = stmt.executeQuery(query2);
                while(rs.next()){
                    int s = rs.getInt("s_no");
                    if(s>song_number){
                        String query3 = "update "+table_name+" set s_no = s_no - 1 where s_no = "+s+";";
                        stmt.executeUpdate(query3);
                    }
                 }
                /*new main_frame().setVisible(true);
                main_frame.this.dispose();*/
                //SwingUtilities.updateComponentTreeUI(this);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"no song deleted!");
        }
       // listsongs.updateUI();     THIS WAS SUPOPSED TO UPDATE THE LIST OF SONGS 
       // ABOVE STATEMENT NEEDS TO BE CHECKED HOWEVER ANOTHER METHOD OF CREATING A NEW FRAME IS NOW IN USE.
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(player!=null){
            int current = listsongs.getSelectedIndex();
            listsongs.setSelectedIndex(--current);
            playbtn.doClick();
        }
        else{
            listsongs.setSelectedIndex(0);
            playbtn.doClick();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void listsongsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listsongsValueChanged
        // TODO add your handling code here:
        song_number = listsongs.getSelectedIndex();
        if(player!=null){
        player.close();
        player = null;
        playbtn.setSelected(false);
        playbtn.setText("play");}
    }//GEN-LAST:event_listsongsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JList<String> listsongs;
    private javax.swing.JToggleButton playbtn;
    private javax.swing.JProgressBar seek;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
